///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      08-jul.-2018 19:23:25
//  Original author: Roberto Piombi
///////////////////////////////////////////////////////////



using System;
using BE;
namespace BE {
	public class Usuario : Persona {

		private String _correo;
		private String _password;
		private String _login;

        public string Correo
        {
            get
            {
                return _correo;
            }

            set
            {
                _correo = value;
            }
        }

        public string Password
        {
            get
            {
                return _password;
            }

            set
            {
                _password = value;
            }
        }

        public string Login
        {
            get
            {
                return _login;
            }

            set
            {
                _login = value;
            }
        }
        public override string ToString()
        {
            return _login;
        }
    }

}